"""
Author: Andrew Bieber <andrewbieber.work@gmail.com>
File: compare_metrics.py
Description:
    Compare one swing's extracted feature metrics against the professional
    baseline generated by the batch pipeline.

    This module does not calculate new mechanics. It interprets existing
    feature values against the pro median/IQR baseline.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


CORE_METRICS = {
    "head_movement_start_to_contact": {
        "label": "Head movement",
        "unit": "normalized units",
        "note": "Lower values generally suggest more head stability through the swing window.",
    },
    "hand_path_start_to_contact": {
        "label": "Hand path distance",
        "unit": "normalized units",
        "note": "Measures wrist-path movement from swing start to contact proxy.",
    },
    "frames_peak_hand_speed_to_contact": {
        "label": "Peak hand speed to contact",
        "unit": "frames",
        "note": "Measures how many frames occur between peak wrist speed and the contact proxy.",
    },
}


EXPERIMENTAL_METRICS = {
    "shoulder_angle_change_start_to_contact": {
        "label": "Shoulder angle change",
        "unit": "degrees",
        "note": "Experimental. Current angle calculation may suffer from wraparound artifacts.",
    },
    "frames_start_to_contact": {
        "label": "Movement start to contact",
        "unit": "frames",
        "note": "Experimental. Sensitive to clip trimming, speed, and event detection quality.",
    },
    "frames_start_to_peak_hand_speed": {
        "label": "Movement start to peak hand speed",
        "unit": "frames",
        "note": "Experimental. Sensitive to clip trimming, speed, and event detection quality.",
    },
}


def load_json(path: Path) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def save_json(data: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as file:
        json.dump(data, file, indent=4)


def finite_float(value: Any) -> float | None:
    """
    Convert a value to a finite float.

    Returns None for:
        - missing values
        - non-numeric values
        - NaN
        - infinity
    """
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None

    if not math.isfinite(number):
        return None

    return number


def format_number(value: Any, digits: int = 4) -> str:
    number = finite_float(value)

    if number is None:
        return "N/A"

    return f"{number:.{digits}f}"


def compare_metric(
    metric_name: str,
    metric_info: dict[str, str],
    sample_features: dict[str, Any],
    baseline: dict[str, Any],
    min_baseline_count: int = 5,
) -> dict[str, Any]:
    """
    Compare one sample metric against pro baseline q1/median/q3.
    """
    baseline_features = baseline.get("features", {})
    baseline_stats = baseline_features.get(metric_name)

    sample_value = finite_float(sample_features.get(metric_name))

    result = {
        "metric": metric_name,
        "label": metric_info["label"],
        "unit": metric_info["unit"],
        "sample_value": sample_value,
        "pro_median": None,
        "pro_q1": None,
        "pro_q3": None,
        "pro_count": 0,
        "status": "not_evaluated",
        "interpretation": "",
        "note": metric_info["note"],
    }

    if sample_value is None:
        result["status"] = "missing_sample_metric"
        result["interpretation"] = (
            "The sample swing did not produce a valid finite value for this metric."
        )
        return result

    if not baseline_stats:
        result["status"] = "missing_baseline_metric"
        result["interpretation"] = (
            "The professional baseline does not include this metric."
        )
        return result

    pro_count = int(baseline_stats.get("count", 0))
    pro_median = finite_float(baseline_stats.get("median"))
    pro_q1 = finite_float(baseline_stats.get("q1"))
    pro_q3 = finite_float(baseline_stats.get("q3"))

    result["pro_count"] = pro_count
    result["pro_median"] = pro_median
    result["pro_q1"] = pro_q1
    result["pro_q3"] = pro_q3

    if pro_count < min_baseline_count:
        result["status"] = "insufficient_baseline_samples"
        result["interpretation"] = (
            f"Only {pro_count} valid professional samples were available. "
            f"At least {min_baseline_count} are required for comparison."
        )
        return result

    if pro_median is None or pro_q1 is None or pro_q3 is None:
        result["status"] = "invalid_baseline_stats"
        result["interpretation"] = (
            "The professional baseline stats for this metric are incomplete or invalid."
        )
        return result

    if sample_value < pro_q1:
        result["status"] = "below_pro_middle_50"
        result["interpretation"] = (
            "The sample value is below the middle 50% range of the pro baseline."
        )
    elif sample_value > pro_q3:
        result["status"] = "above_pro_middle_50"
        result["interpretation"] = (
            "The sample value is above the middle 50% range of the pro baseline."
        )
    else:
        result["status"] = "within_pro_middle_50"
        result["interpretation"] = (
            "The sample value falls within the middle 50% range of the pro baseline."
        )

    if pro_median != 0:
        result["difference_from_median"] = sample_value - pro_median
        result["percent_difference_from_median"] = (
            (sample_value - pro_median) / abs(pro_median)
        ) * 100.0
    else:
        result["difference_from_median"] = sample_value - pro_median
        result["percent_difference_from_median"] = None

    return result


def build_markdown_report(
    sample_name: str,
    baseline: dict[str, Any],
    core_results: list[dict[str, Any]],
    experimental_results: list[dict[str, Any]],
) -> str:
    """
    Build a markdown report comparing one swing against the pro baseline.
    """
    baseline_group = baseline.get("group", "pro")
    sample_count = baseline.get("sample_count", "unknown")

    lines = [
        f"# Swing Comparison Report: {sample_name}",
        "",
        "## Purpose",
        "",
        (
            "This report compares one test swing against the professional baseline "
            "generated by the batch video analysis pipeline."
        ),
        "",
        "This is an exploratory comparison, not a coaching diagnosis.",
        "",
        "---",
        "",
        "## Baseline",
        "",
        f"- Baseline group: `{baseline_group}`",
        f"- Baseline sample count: `{sample_count}`",
        "- Method: median and interquartile range over pose-derived swing metrics",
        "",
        "---",
        "",
        "## Core Metrics",
        "",
        "| Metric | Sample Value | Pro Q1 | Pro Median | Pro Q3 | Status |",
        "|---|---:|---:|---:|---:|---|",
    ]

    for result in core_results:
        lines.append(
            "| "
            f"{result['label']} | "
            f"{format_number(result['sample_value'])} | "
            f"{format_number(result['pro_q1'])} | "
            f"{format_number(result['pro_median'])} | "
            f"{format_number(result['pro_q3'])} | "
            f"{result['status']} |"
        )

    lines.extend(
        [
            "",
            "### Core Metric Notes",
            "",
        ]
    )

    for result in core_results:
        lines.extend(
            [
                f"#### {result['label']}",
                "",
                f"- Metric key: `{result['metric']}`",
                f"- Unit: {result['unit']}",
                f"- Interpretation: {result['interpretation']}",
                f"- Note: {result['note']}",
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "## Experimental / Noisy Metrics",
            "",
            (
                "These metrics are reported for transparency, but they should not be "
                "treated as strong conclusions yet."
            ),
            "",
            "| Metric | Sample Value | Pro Q1 | Pro Median | Pro Q3 | Status |",
            "|---|---:|---:|---:|---:|---|",
        ]
    )

    for result in experimental_results:
        lines.append(
            "| "
            f"{result['label']} | "
            f"{format_number(result['sample_value'])} | "
            f"{format_number(result['pro_q1'])} | "
            f"{format_number(result['pro_median'])} | "
            f"{format_number(result['pro_q3'])} | "
            f"{result['status']} |"
        )

    lines.extend(
        [
            "",
            "### Experimental Metric Notes",
            "",
        ]
    )

    for result in experimental_results:
        lines.extend(
            [
                f"#### {result['label']}",
                "",
                f"- Metric key: `{result['metric']}`",
                f"- Unit: {result['unit']}",
                f"- Interpretation: {result['interpretation']}",
                f"- Note: {result['note']}",
                "",
            ]
        )

    lines.extend(
        [
            "---",
            "",
            "## Interpretation Guardrails",
            "",
            "- The professional baseline is not an ideal swing model.",
            "- Values are pose-derived estimates, not ground-truth biomechanics.",
            "- Camera angle, clip trimming, frame rate, and pose detection quality affect the metrics.",
            "- Contact is a proxy because the bat and ball are not tracked.",
            "- This report is useful for system evaluation and exploratory comparison, not final coaching advice.",
            "",
        ]
    )

    return "\n".join(lines)


def run_comparison(
    features_path: Path,
    baseline_path: Path,
    output_path: Path,
    sample_name: str | None = None,
) -> None:
    """
    Compare one feature JSON file against the pro baseline.
    """
    sample_features = load_json(features_path)
    baseline = load_json(baseline_path)

    if sample_name is None:
        sample_name = features_path.stem.replace("_features", "")

    core_results = [
        compare_metric(
            metric_name=metric_name,
            metric_info=metric_info,
            sample_features=sample_features,
            baseline=baseline,
        )
        for metric_name, metric_info in CORE_METRICS.items()
    ]

    experimental_results = [
        compare_metric(
            metric_name=metric_name,
            metric_info=metric_info,
            sample_features=sample_features,
            baseline=baseline,
        )
        for metric_name, metric_info in EXPERIMENTAL_METRICS.items()
    ]

    report = build_markdown_report(
        sample_name=sample_name,
        baseline=baseline,
        core_results=core_results,
        experimental_results=experimental_results,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as file:
        file.write(report)

    json_output_path = output_path.with_suffix(".json")
    save_json(
        {
            "sample_name": sample_name,
            "features_path": str(features_path),
            "baseline_path": str(baseline_path),
            "core_results": core_results,
            "experimental_results": experimental_results,
        },
        json_output_path,
    )

    print(f"Saved comparison report to: {output_path}")
    print(f"Saved comparison JSON to: {json_output_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare one swing feature file against a professional baseline."
    )

    parser.add_argument(
        "--features",
        type=Path,
        required=True,
        help="Path to the sample feature JSON file.",
    )

    parser.add_argument(
        "--baseline",
        type=Path,
        default=Path("outputs/aggregate/pro_baseline.json"),
        help="Path to the professional baseline JSON file.",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Path where the markdown comparison report should be saved.",
    )

    parser.add_argument(
        "--sample-name",
        type=str,
        default=None,
        help="Readable name for the sample swing.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    features_path = args.features
    sample_name = args.sample_name

    if sample_name is None:
        sample_name = features_path.stem.replace("_features", "")

    if args.output is None:
        output_path = (
            Path("outputs")
            / "comparisons"
            / f"{sample_name}_vs_pro_baseline.md"
        )
    else:
        output_path = args.output

    run_comparison(
        features_path=features_path,
        baseline_path=args.baseline,
        output_path=output_path,
        sample_name=sample_name,
    )


if __name__ == "__main__":
    main()